
version: '3.7'

services:

  avatars-client:
    build:
      context: client
    image: cyberdojo/avatars-client
    init: true
    container_name: test-avatars-client
    user: nobody
    read_only: true
    tmpfs: /tmp
    restart: "no"
    ports: [ "5028:5028" ]

  avatars-server:
    build:
      context: app
      args: [ COMMIT_SHA ]
    image: ${CYBER_DOJO_AVATARS_IMAGE}
    container_name: test-avatars-server
    environment: [ NO_PROMETHEUS ]
    ports: [ "${CYBER_DOJO_AVATARS_PORT}:${CYBER_DOJO_AVATARS_PORT}" ]
    init: true
    user: nobody
    read_only: true
    restart: "no"
    volumes: [ "./test_server:/app/test:ro" ]
    tmpfs: [ "/tmp:exec,mode=1777" ] # Sticky bit must be set on /tmp otherwise
                                     # Dir.mktmpdir(id,'/tmp') complains
