
version: '3.7'

services:

  avatars-client:
    build:
      context: client
      args: [ CYBER_DOJO_AVATARS_CLIENT_PORT ]
    image: cyberdojo/avatars-client
    container_name: test-avatars-client
    env_file:
      - .env    
    user: ${CYBER_DOJO_AVATARS_CLIENT_USER}
    read_only: true
    tmpfs: /tmp
    restart: "no"
    ports: [ "${CYBER_DOJO_AVATARS_CLIENT_PORT}:${CYBER_DOJO_AVATARS_CLIENT_PORT}" ]

  avatars-server:
    build:
      context: app
      args: [ COMMIT_SHA, CYBER_DOJO_AVATARS_PORT ]
    image: ${CYBER_DOJO_AVATARS_IMAGE}
    container_name: test-avatars-server
    env_file:
      - .env
    ports: [ "${CYBER_DOJO_AVATARS_PORT}:${CYBER_DOJO_AVATARS_PORT}" ]
    user: ${CYBER_DOJO_AVATARS_SERVER_USER}
    read_only: true
    restart: "no"
    volumes: [ "./test_server:/app/test:ro" ]
    tmpfs: [ "/tmp:exec,mode=1777" ] # Sticky bit must be set on /tmp otherwise
                                     # Dir.mktmpdir(id,'/tmp') complains
